force-app/main/default/objects/Lead_Callout_Log__c/Lead_Callout_Log__c.object-meta.xml
<CustomObject>
    <label>Lead Callout Log</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>Lead Callout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Callout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Callout_Log__c/fields/Dump__c.field-meta.xml
<CustomField>
    <fullName>Dump__c</fullName>
    <description>Log dump</description>
    <label>Dump</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lead_Callout_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of callout</description>
    <label>Status</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadQueueableNode.cls
public without sharing class LeadQueueableNode extends QueueableBaseNode {
    
    private Lead lead;
    private HttpResponseWrapper resp;
    private static final string ENDPOINT ='https://httpdump.app/dumps/b20b1a16-63dd-4d8d-96eb-bdd53179d5ff';

    public LeadQueueableNode(Lead lead) {
        this.lead = lead;
    }


    public override void execute(){
        SendLeadRequest request = new SendLeadRequest(this.lead);
        HttpRequest req = new HttpRequest();
        req.setEndpoint(ENDPOINT);
        req.setHeader('Content-Type', 'application/json');
        req.setBody(JSON.serialize(request));
        req.setMethod('POST');
        resp = new HttpResponseWrapper(new Http().send(req));

    }

    public override void finish(){

        Lead_Callout_Log__c log = new Lead_Callout_Log__c();
        log.status__c = resp.status;
        log.Dump__c = resp.body;

        parent.addResult(log);

    }

    public class HttpResponseWrapper{
        public string status;
        public string body;

        public HttpResponseWrapper(HttpResponse resp){
            status = resp.getStatus();
            body = resp.getBody();

        }
    }
}