force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <label>Subscriber</label>
    <nameField>
        <label>Subscriber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Data_Used__c.field-meta.xml
<CustomField>
    <fullName>Data_Used__c</fullName>
    <description>A measure of the data used by the subscriber in GB</description>
    <label>Data Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <description>Date joined by subscriber</description>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>subscriber email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>subscriber status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>SUSPENDED</fullName>
            </value>
            <value>
                <fullName>DISCONNECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubscriberEnhancedListLwcController.cls
@suppressWarnings('pmd')
public without sharing class SubscriberEnhancedListLwcController {
    



    @AuraEnabled(cacheable=true)
    public static List<SubscriberLwcTableData> getAllSubscribers(boolean throwException){
        List<SubscriberLwcTableData> data = new List<SubscriberLwcTableData>();
        try {
            for(Subscriber__c sub : [Select Id ,Name, Phone__c, Email__c , Country__c , Status__c , Date_Joined__c , Data_Used__c From Subscriber__c]){
                data.add(new SubscriberLwcTableData(sub));
            }
            if(throwException){
                throw new IllegalArgumentException('Intentionally throwing this exception to cover for test. Normally we wouldnt do this in real life');
            }
            return data;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


}