force-app/main/default/objects/Lead/fields/Bot_Script__c.field-meta.xml
<CustomField>
    <fullName>Bot_Script__c</fullName>
    <description>The bot script to run for this Lead</description>
    <label>Bot Script</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ej90</fullName>
            </value>
            <value>
                <fullName>ej100</fullName>
            </value>
            <value>
                <fullName>ej200</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Callout_Log__c/Lead_Callout_Log__c.object-meta.xml
<CustomObject>
    <label>Lead Callout Log</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>Lead Callout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Callout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadTriggerOperationTests.cls
@suppressWarnings('pmd')
@isTest
public with sharing class LeadTriggerOperationTests {

    @IsTest
    static void testCreateLeads(){
        Test.setMock(System.HttpCalloutMock.class, new LogCalloutMock());
        Test.startTest();
        insert TestDataFactory.getTestLeads(4,'ej90');
        Test.stopTest();

        integer logCount = [Select COUNT() from Lead_Callout_Log__c ];
        System.assertEquals(4, logCount);

        
    }

    @IsTest
    static void testUpdateLeads(){
        Test.setMock(System.HttpCalloutMock.class, new LogCalloutMock());
        List<Lead> testPreviousLeads = TestDataFactory.getTestLeads(4,'ej100');
        insert testPreviousLeads;
        Test.startTest();
        for(Lead l : testPreviousLeads){
            l.Bot_Script__c ='ej90';
        }
        update testPreviousLeads;
        Test.stopTest();
        
    }




}