force-app/main/default/objects/Lead/fields/Bot_Script__c.field-meta.xml
<CustomField>
    <fullName>Bot_Script__c</fullName>
    <description>The bot script to run for this Lead</description>
    <label>Bot Script</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ej90</fullName>
            </value>
            <value>
                <fullName>ej100</fullName>
            </value>
            <value>
                <fullName>ej200</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <label>Subscriber</label>
    <nameField>
        <label>Subscriber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Data_Used__c.field-meta.xml
<CustomField>
    <fullName>Data_Used__c</fullName>
    <description>A measure of the data used by the subscriber in GB</description>
    <label>Data Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Date_Joined__c.field-meta.xml
<CustomField>
    <fullName>Date_Joined__c</fullName>
    <description>Date joined by subscriber</description>
    <label>Date Joined</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>subscriber email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>subscriber status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>SUSPENDED</fullName>
            </value>
            <value>
                <fullName>DISCONNECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public without sharing class TestDataFactory {
   

    public static Account getTestAccount(){
        Account acc = new Account(Name='Test Account');
        acc.AccountNumber='1234567890';
        acc.Website='https://mysite.com';

        return acc;
    }

    public static List<Lead> getTestLeads(integer numberOfLeads, string testScript){
        List<Lead> myLeads = new List<Lead>();
        
        for(integer i =1 ; i <= numberOfLeads ;i++){
            Lead myLead = new Lead();
            mylead.FirstName ='Test Lead ';
            mylead.LastName = String.valueOf(i);
            myLead.Bot_Script__c=testScript;
            myLead.Company='Test Company' + i;
            myLead.Email ='TestLead'+i+'@testmaildomain.com';
            myLead.phone= '+123'+String.join(new List<Integer>{i,i,i,i,i,i,i,i,i,i},'');
            myLeads.add(myLead);

        }
        return myLeads;

    }

    public static List<Subscriber__c> getTestSubscribers(integer amount){
        List<Subscriber__c> subs = new List<Subscriber__c>();
        for(integer i = 1; i <= amount ; i++){
            Subscriber__c sub = new Subscriber__c();
            sub.Name = 'Test Sub ' + i;
            sub.Country__c = 'Nigeria';
            sub.Email__c = 'testsub'+i+'@testemaildomain.com';
            sub.Phone__c = '+234'+String.join(new List<Integer>{i,i,i,i,i,i,i,i,i,i}, '');
            sub.Status__c = i  < 3 ?  'ACTIVE' : Math.mod(i, 2) == 0 ? 'SUSPENDED' : 'DISCONNECTED';
            sub.Date_Joined__c = Date.today().addDays(i);
            sub.Data_Used__c = Math.random() * 50 * i;
            subs.add(sub);
        }

        return subs;


    }
}